### ISSUE TITLE
Never splits

### ISSUE THREAD

**Issue by AndyH24** [fmichea/sm64-livesplit-autosplitter#18]
I have followed the install directions and am trying to get the autosplitter to run on project64. I have my splits set up but it never autosplits whether I start the splits manually or let it try to autosplit itself.

**Comment by fmichea** [comment]
Hello @AndyH24,

After following the [Stable version installation guide](https://github.com/fmichea/sm64-livesplit-autosplitter#stable-version), was the script able to do anything? For instance, does the timer reset on emulator reset?

I think this can be either an issue of the script not loading at all, or of the splitter instructions not being read correctly by the script, so we have to find which case it is first. Make sure to only run one Project64 at a time, otherwise LiveSplit might connect to the wrong one and make it look like the auto-splitter is not active.

I can highly recommend joining the [SM64 Discord server](https://discord.com/invite/sm64) and asking in the #technical_help channel for troubleshooting help. I or others will be happy to help you get it working there.

**Comment by AndyH24** [comment]
I am sorry for not replying sooner. I fixed the issue by redoing the coordinates as I was viewing more than just the gameplay. Then after doing that I realized that I had my life as a lag frame counter and changed that back to normal and that seemed to fix it.

**Comment by fmichea** [comment]
Oh are you using AutoSplit64? This isn't usually recommended if you play on emulator, this LiveSplit script is the recommendation because instead of relying on visual cues from screen recording, it reads SM64 memory directly which is a lot more accurate and reliable. But if you got AutoSplit64 working then you can feel free to keep using that :)
