### ISSUE TITLE
Current reset method cuts off sound clips

### ISSUE THREAD

**Issue by Malkierian** [fmichea/sm64-livesplit-autosplitter#7]
Because you reset twice during the process of resetting the timer on emu restart, any sound clips set in LS for "on reset" get cut off within a second of starting. Would be better if you just restarted the timer at the appropriate time instead of stopping and starting the timer.

**Comment by fmichea** [comment]
Thank you, I will take a look at this during the week-end

**Comment by fmichea** [comment]
Fixed in latest release, to use: enable the option for delayed resets (under EXPERT > General) which will make the two separate events "reset" and "start" the same frame and will somehow make live split not cut out the sound. I made it an option as it might be preference about how the timer behaves.
