### ISSUE TITLE
Different Format for entry/exit

### ISSUE THREAD

**Issue by Malkierian** [fmichea/sm64-livesplit-autosplitter#9]
Instead of having "entry/exit=" in the splits, maybe do something like Aglab did with [] being entry codes (I know you can't use [] at this point because you treated them interchangeably with (), but {} is still available). It just feels clunky having to have that in there, and doesn't fit with the rest of the apparent theme of the splitter syntax in making split names look good.

**Comment by fmichea** [comment]
hey Malkierian, sorry I did not respond sooner to this request

The format here is actually made to be a bit more flexible looking forward with more advanced splitting conditions without making even more special characters trigger AS (since I already look at `()` and `[]`). There is another such option for star door touch already, maybe more in the future. 

But I do agree this does not look great. To fix that I have now released a LiveSplit layout change which hides this stuff from what's displayed, I know you've tried it. This to me is the better fix, because it unlocks all the flexibility I need while also allowing anything to be hidden and therefore keep clean splits displayed.

Please let me know if you think this isn't properly addressed but I'll assume the LiveSplit layout solve this issue for now. Cheers for the reports also.
